version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    # Skip patch version bumps
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-sphinx-theme"
        - "ansys-tools-common"
        - "ansys-tools-visualization-interface"
        - "ansys-pythonnet"
        - "pyedb"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    # NOTE: if the 'prefix' is changed, the changes must be adapted in label.yml
    commit-message:
      prefix: "BUILD(uv)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    # Skip patch version bumps
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    cooldown:
      default-days: 10 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    # NOTE: if the 'prefix' is changed, the changes must be adapted in label.yml
    commit-message:
      prefix: "BUILD(actions)"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    # Skip patch version bumps
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    cooldown:
      default-days: 7 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/pre-commit-hooks"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(pre-commit)"