comment:
  layout: "diff"
  behavior: default

coverage:
  status:
    patch:
      default:
        # basic
        target: 90%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
