ignore:
  - "src/ansys/aedt/core/rpc/*.py"
  - "src/ansys/aedt/core/misc/*.py"
  - "src/ansys/aedt/core/visualization/advanced/sbrplus/hdm_utils.py"
  - "src/ansys/aedt/core/workflows/installer"
  - "src/ansys/aedt/core/workflows/templates"
  - "src/ansys/aedt/core/common_rpc.py"
  - "src/ansys/aedt/core/generic/grpc_plugin_dll_class.py"
  - "src/ansys/aedt/core/edb.py"
  - "src/ansys/aedt/core/filtersolutions_core" # ignore filtersolutions feature for the current release pending 2025R1 update
  - "src/ansys/aedt/core/filtersolutions.py" # ignore filtersolutions feature for the current release pending 2025R1 update

comment:
  layout: "diff"
  behavior: default

coverage:
  status:
    project: false
    patch:
      default:
        # basic
        target: 85%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error

codecov:
  notify:
    wait_for_ci: yes
