name: 'Restore Testmon Cache'
description: 'Restores testmon data from cache'
inputs:
  testmon-datafile:
    description: 'Path to the testmon data file'
    required: true
    default: '.testmondata'
  cache-key:
    description: 'Base cache key for testmon data'
    required: true
    default: 'testmondata-all'

runs:
  using: "composite"
  steps:
    - name: Restore testmondata cache
      id: testmon-cache
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ inputs.testmon-datafile }}
        key: ${{ inputs.cache-key }}-${{ github.base_ref || 'main' }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ github.base_ref || 'main' }}-
          ${{ inputs.cache-key }}-main-

    - name: Check testmon cache status
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        TESTMON_FILE: ${{ inputs.testmon-datafile }}
      run: |
          if [ -f "$TESTMON_FILE" ]; then
            echo "Testmon cache restored successfully"
            ls -lh "$TESTMON_FILE"
          else
            echo "No testmon cache found - will run all tests"
          fi
