[Export3D]
name = "Export to 3D"
script = "export_to_3d.py"
icon = "images/large/cad3d.png"
template = "run_pyaedt_toolkit_script"
pip = ""

[PushfromTransient]
name = "Push Excitation from transient data"
script = "push_excitation_from_file_3dl.py"
icon = "images/large/push.png"
template = "run_pyaedt_toolkit_script"
pip = ""
