{% set version = "0.26.1" %}

package:
  name: pyaedt
  version: {{ version }}

source:
  # Use local path instead of PyPI
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10,<4
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10,<4
    - grpcio >=1.50.0,<1.77
    - jsonschema
    - psutil
    - pyedb >=0.24.0,!=0.28.0
    - tomli  # [py<311]
    - tomli-w
    - pyyaml
    - defusedxml >=0.7,<8.0
    - numpy >=1.20.0,<2.3
    - pydantic >=2.6.4,<2.13
    # NOTE: scikit-rf is OPTIONAL - not in requirements

test:
  imports:
    - ansys.aedt.core
    - ansys.aedt.core.visualization.advanced.farfield_visualization
    - ansys.aedt.core.visualization.advanced.touchstone_parser
  commands:
    - python -c "from ansys.aedt.core.visualization.advanced.touchstone_parser import TouchstoneData; print('TouchstoneData imported successfully')"
    - python -c "from ansys.aedt.core.visualization.advanced.farfield_visualization import FfdSolutionData; print('FfdSolutionData imported successfully')"

about:
  home: https://github.com/ansys/pyaedt
  license: MIT
  license_file: LICENSE
  summary: High-level Python API for Ansys Electronics Desktop Framework
  description: |
    PyAEDT is a Python library that interacts directly with the Ansys Electronics
    Desktop (AEDT) API, enabling straightforward and efficient automation in Python.
  dev_url: https://github.com/ansys/pyaedt

extra:
  recipe-maintainers:
    - ansys
