[GenerateReport]
icon = "images/large/pdf.png"
name = "Generate report"
pip = ""
script = "create_report.py"
template = "run_pyaedt_toolkit_script"

[ImportNastran]
icon = "images/large/cad3d.png"
name = "Import Nastran/STL"
pip = ""
script = "import_nastran.py"
template = "run_pyaedt_toolkit_script"

[ConfigureLayout]
icon = "images/large/aedb.png"
name = "Configure layout"
pip = ""
script = "configure_layout.py"
template = "run_pyaedt_toolkit_script"

[FieldsCalculator]
icon = "images/large/fields.png"
name = "Advanced Fields Calculator"
pip = ""
script = "advanced_fields_calculator.py"
template = "run_pyaedt_toolkit_script"
