name: 'Wait for main Cache Update'
description: 'Waits for the main cache update workflow to complete before proceeding with tests'

runs:
  using: 'composite'
  steps:
    - name: Wait for main cache update
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        echo "Checking if main cache update is running..."

        # First check if the workflow file exists on the main branch
        if ! gh api repos/${GITHUB_REPOSITORY}/actions/workflows/update-testmondata-cache.yml --silent 2>/dev/null; then
          echo "::notice::Cache update workflow (update-testmondata-cache.yml) not found on main branch yet."
          echo "::notice::This is expected before the workflow is merged. Skip from now"
          exit 0
        fi

        max_attempts=60
        attempt=0

        while [ $attempt -lt $max_attempts ]; do
          # Check workflow conclusion for base commit
          WORKFLOW_CONCLUSION=$(gh run list \
            --workflow=update-testmondata-cache.yml \
            --branch=main \
            --json status,conclusion,headSha \
            --jq ".[] | select(.headSha == \"$BASE_SHA\") | .conclusion")

          if [ "$WORKFLOW_CONCLUSION" == "success" ]; then
            echo "::notice::main cache update completed successfully"
            break
          elif [ "$WORKFLOW_CONCLUSION" == "failure" ] || [ "$WORKFLOW_CONCLUSION" == "cancelled" ]; then
            echo "::warning::main cache update workflow failed or was cancelled"
            break
          elif [ -z "$WORKFLOW_CONCLUSION" ]; then
            # Check if workflow exists but hasn't completed
            WORKFLOW_EXISTS=$(gh run list \
              --workflow=update-testmondata-cache.yml \
              --branch=main \
              --json headSha \
              --jq ".[] | select(.headSha == \"$BASE_SHA\") | .headSha")

            if [ -z "$WORKFLOW_EXISTS" ]; then
              echo "::notice::No cache update workflow found for base commit (using existing cache)"
              break
            fi
          fi

          attempt=$((attempt + 1))
          echo "::notice::Attempt $attempt/$max_attempts: Cache update still running, waiting 10s..."
          sleep 10
        done

        if [ $attempt -eq $max_attempts ]; then
          echo "::warning::Timeout waiting for cache update. Proceeding anyway..."
        fi
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GH_TOKEN: ${{ github.token }}
