name: 'Wait for main Cache Update'
description: 'Waits for the main cache update workflow to complete before proceeding with tests'

runs:
  using: 'composite'
  steps:
    - name: Wait for main cache update
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        echo "::group::Checking if main cache update is running..."
        echo "Repository: ${GITHUB_REPOSITORY}"
        echo "Base SHA: ${BASE_SHA}"
        echo "Workflow: update-testmondata-cache.yml"
        echo "::endgroup::"

        # First check if the workflow file exists on the main branch
        if ! gh api repos/${GITHUB_REPOSITORY}/actions/workflows/update-testmondata-cache.yml --silent 2>/dev/null; then
          echo "::notice::Cache update workflow (update-testmondata-cache.yml) not found on main branch yet."
          echo "::notice::This is expected before the workflow is merged. Skip for now"
          exit 0
        fi

        echo "::group::Checking for active workflows"
        # Check if there are any running workflows for the base commit
        RUNNING_WORKFLOWS=$(gh run list \
          --workflow=update-testmondata-cache.yml \
          --branch=main \
          --json status,headSha,databaseId \
          --jq "[.[] | select(.headSha == \"$BASE_SHA\" and (.status == \"in_progress\" or .status == \"queued\"))]")

        RUNNING_COUNT=$(echo "$RUNNING_WORKFLOWS" | jq 'length')
        echo "Found $RUNNING_COUNT active workflow(s) for base commit $BASE_SHA"

        if [ "$RUNNING_COUNT" -gt 0 ]; then
          echo "Active workflows:"
          echo "$RUNNING_WORKFLOWS" | jq -r '.[] | "  - Run ID: \(.databaseId), Status: \(.status)"'
        fi
        echo "::endgroup::"

        if [ "$RUNNING_COUNT" -eq 0 ]; then
          echo "::notice::No cache update workflow running for base commit. Proceeding with existing cache."
          exit 0
        fi

        echo "::notice::Waiting for $RUNNING_COUNT workflow(s) to complete..."

        max_attempts=60
        attempt=0

        while [ $attempt -lt $max_attempts ]; do
          WORKFLOW_STATUS=$(gh run list \
            --workflow=update-testmondata-cache.yml \
            --branch=main \
            --json status,conclusion,headSha,databaseId \
            --jq ".[] | select(.headSha == \"$BASE_SHA\")")

          CURRENT_STATUS=$(echo "$WORKFLOW_STATUS" | jq -r '.status // "not_found"')
          CURRENT_CONCLUSION=$(echo "$WORKFLOW_STATUS" | jq -r '.conclusion // "none"')
          RUN_ID=$(echo "$WORKFLOW_STATUS" | jq -r '.databaseId // "unknown"')

          echo "::notice::Attempt $attempt/$max_attempts - Run ID: $RUN_ID, Status: $CURRENT_STATUS, Conclusion: $CURRENT_CONCLUSION"

          if [ "$CURRENT_CONCLUSION" == "success" ]; then
            echo "::notice::main cache update completed successfully"
            exit 0
          elif [ "$CURRENT_CONCLUSION" == "failure" ] || [ "$CURRENT_CONCLUSION" == "cancelled" ]; then
            echo "::error::Cache update workflow failed (conclusion: $CURRENT_CONCLUSION). Cannot proceed with tests."
            exit 1
          fi

          attempt=$((attempt + 1))
          sleep 10
        done

        echo "::error::Timeout waiting for cache update after $((max_attempts * 10)) seconds."
        exit 1
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GH_TOKEN: ${{ github.token }}
