[GenerateReport]
name = "Generate report"
script = "create_report.py"
icon = "images/large/pdf.png"
template = "Run_PyAEDT_Script"
pip = ""

[GenerateReport]
name = "Import Nastran"
script = "import_nastran.py"
icon = "images/large/cad3d.png"
template = "Run_PyAEDT_Script"
pip = ""
