[CreatePowerMap]
name = "Create Power Map from CSV file"
script = "power_map_from_csv.py"
icon = "images/large/push.png"
template = "run_pyaedt_toolkit_script"
pip = ""

[ECADImporter]
name = "ECAD Importer"
script = "ecad_importer.py"
icon = "images/large/ecad.png"
template = "run_pyedb_toolkit_script"
pip = ""