from pyaedt import pyaedt_function_handler
from pyaedt import settings

logger = settings.logger


class COMParameters:
    def __init__(self, physical_layer="50GAUR-1_C2C"):
        self.version = "3.40"
        self.thrusnp = None
        self.fextary = None
        self.nextary = None
        self.spectag = "Customized"
        self.fstthru = "-1"
        self.numport = "-1"
        self.genhtml = "T"
        self.a_dd = "0.05"
        self.a_fe = "0.4"
        self.a_ne = "0.6"
        self.a_ft = None
        self.a_nt = None
        self.a_v = "0.4"
        self.b_max1 = "1.0"
        self.b_min1 = None
        self.b_max2_n_b = None
        self.b_min2_n_b = None
        self.c_1 = "[-0.18:0.02:0]"
        self.c_2 = None
        self.c_3 = None
        self.c_4 = None
        self.c0 = "0.62"
        self.c1 = "[-0.38:0.02:0]"
        self.c2 = None
        self.c3 = None
        self.c_d = "[2.5e-4 2.5e-4]"
        self.c_p = "[1.8e-4 1.8e-4]"
        self.c_v = "0.0"
        self.l_s = None
        self.c_b = None
        self.local_search = None
        self.delta_f = "0.01"
        self.ffe_backoff = "4"
        self.der_0 = "1.0E-5"
        self.eta_0 = "5.2E-8"
        self.f_b = "25.78125"
        self.f_1 = "0.05"
        self.f_2 = "25.78125"
        self.f_min = "0.05"
        self.f_p1 = "6.4453125"
        self.f_p2 = "25.78125"
        self.f_v = "4.0"
        self.f_f = "4.0"
        self.f_n = "4.0"
        self.f_r = "0.75"
        self.f_z = "6.4453125"
        self.g_dc = "[-12:1:0]"
        self.gdc_min = None
        self.g_qual = None
        self.g2_qual = None
        self.l = "2.0"
        self.m = "32.0"
        self.n_b = "14.0"
        self.n_bx = "14.0"
        self.n_b_step = None
        self.r_0 = "50.0"
        self.r_d = "[55 55]"
        self.r_lm = "1.0"
        self.sigma_rj = "0.01"
        self.snr_tx = "27.0"
        self.z_pfext = "[12 30]"
        self.z_pnext = "[12 12]"
        self.z_prx = "[12 30]"
        self.z_pselect = "[1 2]"
        self.z_ptx = "[12 30]"
        self.n_bg = "0"
        self.n_bf = "6"
        self.n_f = None
        self.bmaxg = "0.2"
        self.b_float_rss_max = None
        self.n_tail_start = None
        self.samples_for_c2m = "100"
        self.t_o = None
        self.ac_cm_rms = "0.0"
        self.accm_max_freq = "25.78125"
        self.enforce_causality = None
        self.ec_pulse_tol = "0.01"
        self.ec_diff_tol = "1e-3"
        self.ec_rel_tol = "1e-2"
        self.force_pdf_bin_size = None
        self.pdf_bin_size = "1e-5"
        self.imprsp_trunc_threshold = "1E-3"
        self.n_v = None
        self.vec_pass_threshold = None
        self.com_pass_threshold = "3.0"
        self.erl_pass_threshold = None
        self.eh_max = None
        self.eh_min = None
        self.ctle_type = "CL93"
        self.f_hp_p = None
        self.f_hp_pz = None
        self.f_hp_z = None
        self.g_dc_hp = None
        self.include_pcb = "0.0"
        self.noise_crest_factor = None
        self.pmd_type = "C2C"
        self.max_burst_len = None
        self.err_propagation_com_margin = None
        self.cdr = "MM"
        self.use_eta0_psd = None
        self.tdr_w_txpkg = None
        self.tdr_butterworth = None
        self.butterworth = "TRUE"
        self.bessel_thomson = "FALSE"
        self.bt_order = "4"
        self.runtag = None
        self.sigma_r = "0.02"
        self.histogram_window_weight = "RECTANGLE"
        self.optimize_loop_speed_up = "1"
        self.tdecq = None
        self.port_order = "[1 3 2 4]"
        self.result_dir = None
        self.min_veo_test = None
        self.force_tr = "FALSE"
        self.ideal_tx_term = "0.0"
        self.rx_calibration = "0.0"
        self.sigma_bbn_step = "0.005"
        self.t_r = "0.008"
        self.t_r_filter_type = "FALSE"
        self.t_r_meas_point = "FALSE"
        self.ideal_rx_term = "0.0"
        self.include_ctle = "1.0"
        self.include_tx_rx_filter = "1.0"
        self.inc_package = "1.0"
        self.package_tl_gamma0_a1_a2 = "[0 1.734e-3 1.455e-4]"
        self.package_tl_tau = "0.006141"
        self.package_z_c = "78.2"
        self.board_tl_gamma0_a1_a2 = "[0 4.114e-4 2.547e-4]"
        self.board_tl_tau = "0.006191"
        self.board_z_c = "109.8"
        self.z_bpfext = "72.0"
        self.z_bpnext = "72.0"
        self.z_bprx = "151.0"
        self.z_bptx = "151.0"
        self.cb0 = None
        self.cb1 = None
        self.tdr = "0"
        self.erl = None
        self.z_t = "50"
        self.erl_only = None
        self.tr_tdr = "8.0E-3"
        self.tdr_duration = "5"
        self.n = None
        self.kappa1 = "1.0"
        self.kappa2 = "1.0"
        self.tukey_window = None
        self.beta_x = None
        self.rho_x = None
        self.fixture_delay_time = None
        self.auto_tfx = None
        self.grr_limit = "1"
        self.grr = "1"
        self.gx = None
        self.ffe_pre_tap_len = None
        self.ffe_post_tap_len = None
        self.ffe_tap_step_size = "0"
        self.ffe_main_cur_min = "0.7"
        self.ffe_pre_tap1_max = "0.7"
        self.ffe_post_tap1_max = "0.7"
        self.ffe_tapn_max = "0.7"
        self.cursor_gain = None
        self.sbr_gen_method = "DEFAULT"
        self.fixture_builtin_delay = "500p"

        self.physical_layer = physical_layer

    @property
    def physical_layer(self):
        return self._physical_layer

    @physical_layer.setter
    def physical_layer(self, value):
        self._physical_layer = value
        if value == "50GAUR-1_C2C":
            self.apply_120d_8()
        elif value == "100GBASE-KR4":
            self.apply_93_8()

    @pyaedt_function_handler
    def apply_120d_8(self):
        self.a_dd = "0.02"
        self.a_fe = "0.45"
        self.a_ne = "0.65"
        self.a_ft = None
        self.a_nt = None
        self.a_v = "0.45"
        self.b_max1 = "0.5"
        self.b_min1 = None
        self.b_max2_n_b = None
        self.b_min2_n_b = None
        self.c_1 = "[-0.15:0.05:0]"
        self.c_2 = None
        self.c_3 = None
        self.c_4 = None
        self.c0 = "0.6"
        self.c1 = "[-0.25:0.05:0]"
        self.c2 = None
        self.c3 = None
        self.c_d = "[2.8e-4  2.8e-4]"
        self.c_p = "[1.1e-4 1.1e-4]"
        self.c_v = "0.0"
        self.l_s = None
        self.c_b = None
        self.local_search = None
        self.delta_f = "0.01"
        self.ffe_backoff = "4"
        self.der_0 = "1.0E-5"
        self.eta_0 = "2.6E-8"
        self.f_b = "26.5625"
        self.f_1 = "0.05"
        self.f_2 = "26.5625"
        self.f_min = "0.05"
        self.f_p1 = "10.625"
        self.f_p2 = "1.0E99"
        self.f_v = "4.0"
        self.f_f = "4.0"
        self.f_n = "4.0"
        self.f_r = "0.75"
        self.f_z = "10.625"
        self.g_dc = "[-15:1:0]"
        self.gdc_min = None
        self.g_qual = None
        self.g2_qual = None
        self.l = "4.0"
        self.m = "32.0"
        self.n_b = "10.0"
        self.n_bx = "10.0"
        self.n_b_step = None
        self.r_0 = "50.0"
        self.r_d = "[55 55]"
        self.r_lm = "0.95"
        self.sigma_rj = "0.01"
        self.snr_tx = "31.0"
        self.z_pfext = "[12 30]"
        self.z_pnext = "[12 12]"
        self.z_prx = "[12 30]"
        self.z_pselect = "[1 2 ]"
        self.z_ptx = "[12 30]"
        self.n_bg = "0"
        self.n_bf = "6"
        self.n_f = None
        self.bmaxg = "0.2"
        self.b_float_rss_max = None
        self.n_tail_start = None
        self.samples_for_c2m = "100"
        self.t_o = None
        self.ac_cm_rms = "0.0"
        self.accm_max_freq = "26.5625"
        self.enforce_causality = None
        self.ec_pulse_tol = "0.01"
        self.ec_diff_tol = "1e-3"
        self.ec_rel_tol = "1e-2"
        self.force_pdf_bin_size = None
        self.pdf_bin_size = "1e-5"
        self.imprsp_trunc_threshold = "1E-3"
        self.n_v = None
        self.vec_pass_threshold = None
        self.com_pass_threshold = "3.0"
        self.erl_pass_threshold = "8"
        self.eh_max = None
        self.eh_min = None
        self.ctle_type = "CL93"
        self.f_hp_p = None
        self.f_hp_pz = "0.6640625"
        self.f_hp_z = None
        self.g_dc_hp = "[-4:1:0]"
        self.include_pcb = "0.0"
        self.noise_crest_factor = None
        self.pmd_type = "C2C"
        self.max_burst_len = None
        self.err_propagation_com_margin = None
        self.cdr = "MM"
        self.use_eta0_psd = None
        self.tdr_w_txpkg = None
        self.tdr_butterworth = "1.0"
        self.butterworth = "TRUE"
        self.bessel_thomson = "FALSE"
        self.bt_order = "4"
        self.runtag = "V164"
        self.sigma_r = "0.02"
        self.histogram_window_weight = "RECTANGLE"
        self.optimize_loop_speed_up = "1"
        self.tdecq = None
        self.port_order = "[1 3 2 4]"
        self.result_dir = None
        self.min_veo_test = None
        self.force_tr = "FALSE"
        self.ideal_tx_term = "0.0"
        self.rx_calibration = "0.0"
        self.sigma_bbn_step = "0.005"
        self.t_r = "0.013"
        self.t_r_filter_type = "1.0"
        self.t_r_meas_point = "0.0"
        self.ideal_rx_term = "0.0"
        self.include_ctle = "1.0"
        self.include_tx_rx_filter = "1.0"
        self.inc_package = "1.0"
        self.package_tl_gamma0_a1_a2 = "[0 1.734e-3 1.455e-4]"
        self.package_tl_tau = "0.006141"
        self.package_z_c = "85.0"
        self.board_tl_gamma0_a1_a2 = "[0 4.114e-4 2.547e-4]"
        self.board_tl_tau = "0.006191"
        self.board_z_c = "110.0"
        self.z_bpfext = "72.0"
        self.z_bpnext = "72.0"
        self.z_bprx = "151.0"
        self.z_bptx = "151.0"
        self.cb0 = None
        self.cb1 = None
        self.tdr = "1"
        self.erl = "1.0"
        self.z_t = "50.0"
        self.erl_only = "0.0"
        self.tr_tdr = "0.0189"
        self.tdr_duration = "10.0"
        self.n = None
        self.kappa1 = "1.0"
        self.kappa2 = "1.0"
        self.tukey_window = None
        self.beta_x = "1.07E10"
        self.rho_x = "0.44"
        self.fixture_delay_time = "0.0"
        self.auto_tfx = None
        self.grr_limit = "1"
        self.grr = "1"
        self.gx = None
        self.ffe_pre_tap_len = None
        self.ffe_post_tap_len = None
        self.ffe_tap_step_size = "0"
        self.ffe_main_cur_min = "0.7"
        self.ffe_pre_tap1_max = "0.7"
        self.ffe_post_tap1_max = "0.7"
        self.ffe_tapn_max = "0.7"
        self.cursor_gain = None
        self.sbr_gen_method = "DEFAULT"
        self.fixture_builtin_delay = "500p"

    @pyaedt_function_handler
    def apply_93_8(self):
        self.a_dd = "0.05"
        self.a_fe = "0.4"
        self.a_ne = "0.6"
        self.a_ft = None
        self.a_nt = None
        self.a_v = "0.4"
        self.b_max1 = "1.0"
        self.b_min1 = None
        self.b_max2_n_b = None
        self.b_min2_n_b = None
        self.c_1 = "[-0.18:0.02:0]"
        self.c_2 = None
        self.c_3 = None
        self.c_4 = None
        self.c0 = "0.62"
        self.c1 = "[-0.38:0.02:0]"
        self.c2 = None
        self.c3 = None
        self.c_d = "[2.5e-4 2.5e-4]"
        self.c_p = "[1.8e-4 1.8e-4]"
        self.c_v = "0.0"
        self.l_s = None
        self.c_b = None
        self.local_search = None
        self.delta_f = "0.01"
        self.ffe_backoff = "4"
        self.der_0 = "1.0E-5"
        self.eta_0 = "5.2E-8"
        self.f_b = "25.78125"
        self.f_1 = "0.05"
        self.f_2 = "25.78125"
        self.f_min = "0.05"
        self.f_p1 = "6.4453125"
        self.f_p2 = "25.78125"
        self.f_v = "4.0"
        self.f_f = "4.0"
        self.f_n = "4.0"
        self.f_r = "0.75"
        self.f_z = "6.4453125"
        self.g_dc = "[-12:1:0]"
        self.gdc_min = None
        self.g_qual = None
        self.g2_qual = None
        self.l = "2.0"
        self.m = "32.0"
        self.n_b = "14.0"
        self.n_bx = "14.0"
        self.n_b_step = None
        self.r_0 = "50.0"
        self.r_d = "[55 55]"
        self.r_lm = "1.0"
        self.sigma_rj = "0.01"
        self.snr_tx = "27.0"
        self.z_pfext = "[12 30]"
        self.z_pnext = "[12 12]"
        self.z_prx = "[12 30]"
        self.z_pselect = "[1 2]"
        self.z_ptx = "[12 30]"
        self.n_bg = "0"
        self.n_bf = "6"
        self.n_f = None
        self.bmaxg = "0.2"
        self.b_float_rss_max = None
        self.n_tail_start = None
        self.samples_for_c2m = "100"
        self.t_o = None
        self.ac_cm_rms = "0.0"
        self.accm_max_freq = "25.78125"
        self.enforce_causality = None
        self.ec_pulse_tol = "0.01"
        self.ec_diff_tol = "1e-3"
        self.ec_rel_tol = "1e-2"
        self.force_pdf_bin_size = None
        self.pdf_bin_size = "1e-5"
        self.imprsp_trunc_threshold = "1E-3"
        self.n_v = None
        self.vec_pass_threshold = None
        self.com_pass_threshold = "3.0"
        self.erl_pass_threshold = None
        self.eh_max = None
        self.eh_min = None
        self.ctle_type = "CL93"
        self.f_hp_p = None
        self.f_hp_pz = None
        self.f_hp_z = None
        self.g_dc_hp = None
        self.include_pcb = "0.0"
        self.noise_crest_factor = None
        self.pmd_type = "C2C"
        self.max_burst_len = None
        self.err_propagation_com_margin = None
        self.cdr = "MM"
        self.use_eta0_psd = None
        self.tdr_w_txpkg = None
        self.tdr_butterworth = None
        self.butterworth = "TRUE"
        self.bessel_thomson = "FALSE"
        self.bt_order = "4"
        self.runtag = None
        self.sigma_r = "0.02"
        self.histogram_window_weight = "RECTANGLE"
        self.optimize_loop_speed_up = "1"
        self.tdecq = None
        self.port_order = "[1 3 2 4]"
        self.result_dir = None
        self.min_veo_test = None
        self.force_tr = "FALSE"
        self.ideal_tx_term = "0.0"
        self.rx_calibration = "0.0"
        self.sigma_bbn_step = "0.005"
        self.t_r = "0.008"
        self.t_r_filter_type = "FALSE"
        self.t_r_meas_point = "FALSE"
        self.ideal_rx_term = "0.0"
        self.include_ctle = "1.0"
        self.include_tx_rx_filter = "1.0"
        self.inc_package = "1.0"
        self.package_tl_gamma0_a1_a2 = "[0 1.734e-3 1.455e-4]"
        self.package_tl_tau = "0.006141"
        self.package_z_c = "78.2"
        self.board_tl_gamma0_a1_a2 = "[0 4.114e-4 2.547e-4]"
        self.board_tl_tau = "0.006191"
        self.board_z_c = "109.8"
        self.z_bpfext = "72.0"
        self.z_bpnext = "72.0"
        self.z_bprx = "151.0"
        self.z_bptx = "151.0"
        self.cb0 = None
        self.cb1 = None
        self.tdr = "0"
        self.erl = None
        self.z_t = "50"
        self.erl_only = None
        self.tr_tdr = "8.0E-3"
        self.tdr_duration = "5"
        self.n = None
        self.kappa1 = "1.0"
        self.kappa2 = "1.0"
        self.tukey_window = None
        self.beta_x = None
        self.rho_x = None
        self.fixture_delay_time = None
        self.auto_tfx = None
        self.grr_limit = "1"
        self.grr = "1"
        self.gx = None
        self.ffe_pre_tap_len = None
        self.ffe_post_tap_len = None
        self.ffe_tap_step_size = "0"
        self.ffe_main_cur_min = "0.7"
        self.ffe_pre_tap1_max = "0.7"
        self.ffe_post_tap1_max = "0.7"
        self.ffe_tapn_max = "0.7"
        self.cursor_gain = None
        self.sbr_gen_method = "DEFAULT"
        self.fixture_builtin_delay = "500p"
