[ConverttoCircuit]
name = "Export to Circuit"
script = "convert_to_circuit.py"
icon = "images/large/export_to_circuit.png"
template = "run_pyaedt_toolkit_script"
url = "https://aedt.docs.pyansys.com/version/stable/User_guide/pyaedt_extensions_doc/twinbuilder/convert_to_circuit.html"
