[Console]
name = "PyAEDT Console"
script = "console_setup.py"
icon = "console.png"
template = "PyAEDT_Console"

[Jupyter]
name = "Jupyter Notebook"
script = "jupyter_template.ipynb"
icon = "jupyter.png"
template = "Jupyter"

[Run_Script]
name = "Run PyAEDT Script"
script = ""
icon = "run_script.png"
template = "Run_PyAEDT_Script"

[ToolkitManager]
name = "Extension Manager"
script = "extension_manager.py"
icon = "extension_manager.png"
template = "Run_Extension_Manager"
