[voltage]
name = "Voltage_Line"
description = "Voltage Drop along a Line"
design_type = ["HFSS", "Q3D Extractor"]
fields_type = ["Fields", "CG Fields"]
assignment = ""
assignment_type = ["Line"]
operations = ["Fundamental_Quantity('E')",
    "Operation('Real')",
    "Operation('Tangent')",
    "Operation('Dot')",
    "EnterLine('assignment')",
    "Operation('LineValue')",
	"Operation('Integrate')",
	"Operation('CmplxR')",
	"Fundamental_Quantity('E')",
	"Operation('Imag')",
	"Operation('Tangent')",
	"Operation('Dot')",
	"EnterLine('assignment')",
	"Operation('LineValue')",
	"Operation('Integrate')",
	"Operation('CmplxI')",
	"Operation('+')"]
report = ["Data Table", "Rectangular Plot"]