name: night
on:
  schedule:  # UTC at 0300
    - cron:  '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests-smoke:
    name: "Tests / Smoke / ${{ matrix.os }} / Python ${{ matrix.python-version}} / ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    if: |
      !contains(github.event.pull_request.labels.*.name, 'ci:skip') &&
      !contains(github.event.pull_request.labels.*.name, 'tests:skip') &&
      !contains(github.event.pull_request.labels.*.name, 'tests:smoke:skip')
    needs: style
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        target: ['all', 'installer']
        exclude:
          - python-version: '3.7'
            target: 'installer'
    steps:
      - uses: ansys/actions/build-wheelhouse@v6
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          target: ${{ matrix.target }}


