name: release
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "release/*.*"

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: 'pyaedt'
  DOCUMENTATION_CNAME: 'aedt.docs.pyansys.com'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_HOST_URL: ${{ vars.MEILISEARCH_HOST_URL }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}
  ON_CI: True
  VTK_OSMESA_VERSION: '9.2.20230527.dev0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  style:
    name: "Style checks"
    runs-on: ubuntu-latest
    steps:

      # TODO: Update to ansys/actions/doc-style@v6
      - name: "Style of doc"
        uses: ansys/actions/doc-style@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          vale-config: "doc/.vale.ini"
          vale-version: "2.29.6"

  doc-build:
    name: Documentation build with examples
    runs-on: [ self-hosted, Windows, pyaedt ]
    timeout-minutes: 720
    needs: style
    steps:
      - name: Install Git and checkout project
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create virtual environment
        run: |
          python -m venv .venv
          .venv\Scripts\Activate.ps1
          python -m pip install pip -U
          python -m pip install wheel setuptools -U
          python -c "import sys; print(sys.executable)"

      - name: Install pyaedt and documentation dependencies
        run: |
          .venv\Scripts\Activate.ps1
          pip install .[doc]

      - name: Retrieve PyAEDT version
        id: version
        run: |
          .venv\Scripts\Activate.ps1
          echo "PYAEDT_VERSION=$(python -c 'from pyaedt import __version__; print(__version__)')" >> $GITHUB_OUTPUT
          echo "PyAEDT version is: $(python -c "from pyaedt import __version__; print(__version__)")"

      - name: Install CI dependencies (e.g. vtk-osmesa)
        run: |
          .venv\Scripts\Activate.ps1
          # Uninstall conflicting dependencies
          pip uninstall --yes vtk
          pip install --extra-index-url https://wheels.vtk.org vtk-osmesa==9.2.20230527.dev0

      # TODO: Update this step once pyaedt-examples is ready
      # NOTE: Use environment variable to keep the doctree and avoid redundant build for PDF pages
      - name: Build HTML documentation with examples
        env:
          SPHINXBUILD_KEEP_DOCTREEDIR: "1"
        run: |
          .venv\Scripts\Activate.ps1
          .\doc\make.bat clean
          .\doc\make.bat html

      # TODO: Keeping this commented as reminder of https://github.com/ansys/pyaedt/issues/4296
      # # Verify that sphinx generates no warnings
      # - name: Check for warnings
      #   run: |
      #     .venv\Scripts\Activate.ps1
      #     python doc/print_errors.py

      # Use environment variable to remove the doctree after the build of PDF pages
      - name: Build PDF documentation with examples
        env:
          SPHINXBUILD_KEEP_DOCTREEDIR: "0"
        run: |
          .venv\Scripts\Activate.ps1
          .\doc\make.bat pdf

      - name: Add assets to HTML docs
        run: |
          zip -r documentation-html.zip ./doc/_build/html
          mv documentation-html.zip ./doc/_build/html/_static/assets/download/
          cp doc/_build/latex/PyAEDT-Documentation-*.pdf ./doc/_build/html/_static/assets/download/pyaedt.pdf

      - name: Upload HTML documentation with examples artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-html
          path: doc/_build/html
          retention-days: 7

      - name: Upload PDF documentation without examples artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: doc/_build/latex/PyAEDT-Documentation-*.pdf
          retention-days: 7

  tests-linux:
    name: "Linux / Tests / ${{ matrix.tests.name }}"
    needs: style
    runs-on: [ self-hosted, Linux, pyaedt ]
    env:
      ANSYSEM_ROOT241: '/opt/AnsysEM/v241/Linux64'
      ANS_NODEPCHECK: '1'
    strategy:
      fail-fast: false
      matrix:
        tests:
          - {name: "Units", label: "units", folder: "_unittest", flags: "-n 4 --dist loadfile"}
          - {name: "Solvers", label: "solvers", folder: "_unittest_solvers", flags: ""}
    steps:

      - name: "Checkout project"
        uses: actions/checkout@v4

      - name: "Setup Python ${{ env.MAIN_PYTHON_VERSION }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Create a virtual environment"
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade \
            --trusted-host pypi.org \
            --trusted-host pypi.python.org \
            --trusted-host files.pythonhosted.org \
            pip

      - name: "Install tests dependencies"
        run: |
          source .venv/bin/activate
          python -m pip install .[tests] pytest-azurepipelines

      - name: "Install graphics dependencies"
        run: |
          source .venv/bin/activate
          python -m pip uninstall --yes vtk
          python -m pip install --extra-index-url https://wheels.vtk.org \
            vtk-osmesa==${{ env.VTK_OSMESA_VERSION }}

      - name: "Run ${{ matrix.tests.label }} tests"
        uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          retry_on: error
          timeout_minutes: 50
          command: |
            export LD_LIBRARY_PATH=${{ env.ANSYSEM_ROOT241 }}/common/mono/Linux64/lib64:${{ env.ANSYSEM_ROOT241 }}/Delcross:$LD_LIBRARY_PATH
            source .venv/bin/activate

            pytest ${{ matrix.tests.flags }} \
              --durations=50 -v \
              --cov=pyaedt --cov-report=xml --cov-report=html \
              --junitxml=junit/test-results.xml \
              ${{ matrix.tests.folder }}

      - name: "Upload ${{ matrix.tests.label }} tests coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: linux-${{ matrix.tests.label }}-tests-coverage
          file: ./coverage.xml
          flags: system,solver

      - name: "Upload ${{ matrix.tests.name }} tests results"
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: linux-${{ matrix.tests.label }}-tests-results
          path: junit/test-results.xml

  tests-windows:
    name: "Windows / Tests / ${{ matrix.tests.name }}"
    needs: style
    runs-on: [ self-hosted, Windows, pyaedt ]
    strategy:
      fail-fast: false
      matrix:
        tests:
          - {name: "Units", label: "units", folder: "_unittest", flags: "-n 4 --dist loadfile"}
          - {name: "Solvers", label: "solvers", folder: "_unittest_solvers", flags: ""}
          - {name: "IronPython", label: "ironpython", folder: "_unittest_ironpython", flags: ""}

        tests-skip-units:
           - contains(github.event.pull_request.labels.*.name, 'tests:units:skip')

        tests-skip-solvers:
           - contains(github.event.pull_request.labels.*.name, 'tests:solvers:skip')

        tests-skip-ironpython:
          - contains(github.event.pull_request.labels.*.name, 'tests:ironpython:skip')

        exclude:

          - tests-skip-units: true
            tests:
              - {name: "Units", label: "units", folder: "_unittest", flags: "-n 4 --dist loadfile"}

          - tests-skip-solvers: true
            tests:
              - {name: "Solvers", label: "solvers", folder: "_unittest_solvers", flags: ""}

          - tests-skip-ironpython: true
            tests:
              - {name: "IronPython", label: "ironpython", folder: "_unittest_ironpython", flags: ""}

    steps:

      - name: "Checkout project"
        uses: actions/checkout@v4

      # IronPython tests

      - name: "Tests IronPython"
        if: ${{ matrix.tests.label == 'ironpython' }}
        timeout-minutes: 5
        run: |
          $processA = start-process 'cmd' -ArgumentList '/c .\_unittest_ironpython\run_unittests_batchmode.cmd' -PassThru
          $processA.WaitForExit()

      - name: "Get logger content"
        if: ${{ matrix.tests.label == 'ironpython' }}
        run: |
          get-content .\${{ matrix.tests.folder }}\pyaedt_unit_test_ironpython.log

      - name: "Check for errors"
        if: ${{ matrix.tests.label == 'ironpython' }}
        run: |
          $test_errors_failures = Select-String -Path .\${{ matrix.tests.folder }}\pyaedt_unit_test_ironpython.log -Pattern "TextTestResult errors="
          if ($test_errors_failures -ne $null)
          {
            exit 1
          }

      # Solvers and units tests

      - name: "Setup Python ${{ env.MAIN_PYTHON_VERSION }}"
        if: ${{ matrix.tests.label != 'ironpython' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Create a virtual environment"
        if: ${{ matrix.tests.label != 'ironpython' }}
        run: |
          python -m venv .venv
          .venv\Scripts\Activate.ps1
          python -m pip install --upgrade `
            --trusted-host pypi.org `
            --trusted-host pypi.python.org `
            --trusted-host files.pythonhosted.org `
            pip

      - name: "Install tests dependencies"
        if: ${{ matrix.tests.label != 'ironpython' }}
        run: |
          .venv\Scripts\Activate.ps1
          python -m pip install .[tests] pytest-azurepipelines

      - name: "Install graphics dependencies"
        if: ${{ matrix.tests.label != 'ironpython' }}
        run: |
          .venv\Scripts\Activate.ps1
          python -m pip uninstall --yes vtk
          python -m pip install --extra-index-url https://wheels.vtk.org `
            vtk-osmesa==${{ env.VTK_OSMESA_VERSION }}

      - name: "Run tests"
        uses: nick-fields/retry@v3
        if: ${{ matrix.tests.label != 'ironpython' }}
        env:
          PYTHONMALLOC: malloc
        with:
          max_attempts: 2
          retry_on: error
          timeout_minutes: 50
          command: |
            .venv\Scripts\Activate.ps1

            pytest ${{ matrix.tests.flags }} `
              --durations=50 -v `
              --cov=pyaedt --cov-report=xml --cov-report=html `
              --junitxml=junit/test-results.xml `
              ${{ matrix.tests.folder }}

      - name: "Upload ${{ matrix.tests.label }} tests coverage"
        uses: codecov/codecov-action@v4
        if: ${{ matrix.tests.label != 'ironpython' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: windows-${{ matrix.tests.label }}-tests-coverage
          file: ./coverage.xml
          flags: system

      - name: "Upload ${{ matrix.tests.name }} tests results"
        uses: actions/upload-artifact@v3
        if: ${{ matrix.tests.label != 'ironpython' }}
        with:
          name: windows-${{ matrix.tests.label }}-tests-results
          path: junit/test-results.xml

  build-library:
    name: "Build library"
    needs: [doc-build, tests-linux, tests-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/build-library@v6
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}


  # TODO: Si if we can fix the PDF issue and leverage classic ansys/release-github
  release:
    name: "Release project"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [package, doc-build-with-examples]
    runs-on: ubuntu-latest
    steps:

      - name: "Release to the public PyPI repository"
        uses: ansys/actions/release-pypi-public@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYPI_TOKEN }}

      - name: "Release to GitHub"
        uses: ansys/actions/release-github@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}

  doc-deploy-stable:
    name: "Deploy stable docs"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [release]
    steps:
        uses: ansys/actions/doc-deploy-stable@v6
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          doc-artifact-name: 'documentation-html'

  doc-deploy-index:
    name: "Deploy stable docs index"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: upload-release-doc
    steps:

      - name: "Checkout project"
        uses: actions/checkout@v4

      - name: "Install project dependencies"
        run: |
          python -m pip install -e .

      - name: "Get the version to PyMeilisearch"
        run: |
          VERSION=$(python -c "from pyaedt import __version__; print('.'.join(__version__.split('.')[:2]))")
          VERSION_MEILI=$(python -c "from pyaedt import __version__; print('-'.join(__version__.split('.')[:2]))")
          echo "Calculated VERSION: $VERSION"
          echo "Calculated VERSION_MEILI: $VERSION_MEILI"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_MEILI=$VERSION_MEILI" >> $GITHUB_ENV

      - name: "Deploy the latest documentation index"
        uses: ansys/actions/doc-deploy-index@v6
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}/version/${{ env.VERSION }}
          index-name: pyaedt-v${{ env.VERSION_MEILI }}
          host-url: ${{ env.MEILISEARCH_HOST_URL }}
          api-key: ${{ env.MEILISEARCH_API_KEY }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
