name: Pull request migrator
on:
  issue_comment:
    types: [created]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:

  hk-migrate-fork-pr:
    name: Migrate fork PR to main repository
    runs-on: ubuntu-latest
    # Only runs on issue comments
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request != null &&
      (contains(github.event.comment.body, '@pyansys-ci-bot migrate') ||
      contains(github.event.comment.body, '@pyansys-ci-bot sync'))
    permissions:
      contents: write # Required to push migration branches to the main repository
      pull-requests: write # Required to create pull requests, add comments, and manage reactions
    steps:
      - name: Migrate fork PR
        uses: ansys/actions/hk-migrate-fork-pr@7410037bfb276c79ae91eb3617b9f5d2876f0c94 # v11.0.8
        with:
          pr-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          user-triggering: ${{ github.event.comment.user.login }}
          github-token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-username: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
          team-slug: 'pyaedt-maintainers'