# check spelling, codestyle
name: Style Check

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install style requirements
        run: |
          pip install -r requirements_style.txt --disable-pip-version-check

      - name: black style
        run: |
          python -m black --check -l 120 .

      - name: Codespell
        run: |
          make codespell

      - name: flake8
        if: ${{ always() }}
        run: |
          make flake8
