# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from collections.abc import Callable
from typing import Protocol
from typing import TypeAlias


class _OProject(Protocol):
    """Interface definition for the AEDT project object."""

    def AddDataset(self, *args, **kwargs) -> object: ...
    def ChangeProperty(self, *args, **kwargs) -> object: ...
    def Close(self) -> object: ...
    def CopyDesign(self, *args, **kwargs) -> object: ...
    def Delete(self, *args, **kwargs) -> object: ...
    def DeleteDataset(self, *args, **kwargs) -> object: ...
    def EditDataset(self, *args, **kwargs) -> object: ...
    def ExportDataSet(self, *args, **kwargs) -> object: ...
    def GetActiveDesign(self) -> object: ...
    def GetChildObject(*args) -> object: ...
    def GetDefinitionManager(self, *args, **kwargs) -> object: ...
    def GetDesigns(self) -> object: ...
    def GetName(self) -> object: ...
    def GetPath(self) -> object: ...
    def GetTopDesignList(self) -> object: ...
    def GetVariableValue(self, *args, **kwargs) -> object: ...
    def InsertDesign(self, *args, **kwargs) -> object: ...
    def Paste(self) -> object: ...
    def Rename(self, *args, **kwargs) -> object: ...
    def Save(self) -> object: ...
    def SaveAs(self, *args, **kwargs) -> object: ...
    def SetActiveDesign(self, *args, **kwargs) -> object: ...


class _AppWithOProject(Protocol):
    """Interface definition for PyAEDT app instances."""

    odesign: object
    odesktop: object
    oeditor: object
    oproject: _OProject


AppType: TypeAlias = Callable[..., _AppWithOProject]
"""Type alias for PyAEDT app constructors."""
